name: Mygo_dock_releas

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build and package with goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          workdir: super_calculator/
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      - name: Conexion docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      - name: Create Docker image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./super_calculator
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME}}/macalculatore:1.1.7
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v1.1.7'
          release_name: 'Release 1.1.7'
          draft: false
          prerelease: false
      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-release-artifact
          path: dist/
